package com.dpinta.agenda.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

// GENERADO por tools/gen_tokens_agenda.py desde el sistema de diseño Agenda + CampusWatch
// (tokens.json y alias de tokens.css). No editar a mano: se regenera.

/** Colores del sistema de diseño, tema «claro» y «noche» (README · Color). */
@Immutable
data class AgendaDs(
    val fondo: Color,
    val superficie: Color,
    val superficieFuerte: Color,
    val linea: Color,
    val lineaFuerte: Color,
    val tinta: Color,
    val tintaSuave: Color,
    val deshabilitado: Color,
    val ruta: Color,
    val rutaSuave: Color,
    val sobreRuta: Color,
    val hora: Color,
    val horaSuave: Color,
    val sobreHora: Color,
    val ciruela: Color,
    val ciruelaSuave: Color,
    val sobreCiruela: Color,
    val lineaTrabajo: Color,
    val lineaTrabajoSuave: Color,
    val lineaPersonal: Color,
    val lineaPersonalSuave: Color,
    val lineaEntrega: Color,
    val lineaEntregaSuave: Color,
    val exito: Color,
    val exitoSuave: Color,
    val aviso: Color,
    val avisoSuave: Color,
    val critico: Color,
    val criticoSuave: Color,
    val urgCalma: Color,
    val urgPerdida: Color,
    val lineaUniversidad: Color,
    val lineaExamen: Color,
    val info: Color,
    val urgProxima: Color,
    val urgPronto: Color,
    val urgSalir: Color,
    val urgUrgente: Color,
    val esNoche: Boolean,
)

val AgendaDsClaro = AgendaDs(
    fondo = Color(0xFFF4EEE3),
    superficie = Color(0xFFFFFAF2),
    superficieFuerte = Color(0xFFEBE2D2),
    linea = Color(0xFFD8CCB9),
    lineaFuerte = Color(0xFF8F8291),
    tinta = Color(0xFF251E2B),
    tintaSuave = Color(0xFF665A69),
    deshabilitado = Color(0xFFAA9FA8),
    ruta = Color(0xFF1D5A60),
    rutaSuave = Color(0xFFD9EAE8),
    sobreRuta = Color(0xFFFFFFFF),
    hora = Color(0xFFAD3C24),
    horaSuave = Color(0xFFFBE4D9),
    sobreHora = Color(0xFFFFFFFF),
    ciruela = Color(0xFF7A3A6C),
    ciruelaSuave = Color(0xFFF1DFEA),
    sobreCiruela = Color(0xFFFFFFFF),
    lineaTrabajo = Color(0xFF86600C),
    lineaTrabajoSuave = Color(0xFFF6E8C8),
    lineaPersonal = Color(0xFF4C6B42),
    lineaPersonalSuave = Color(0xFFE3ECDA),
    lineaEntrega = Color(0xFF38578F),
    lineaEntregaSuave = Color(0xFFDFE6F3),
    exito = Color(0xFF2A6B55),
    exitoSuave = Color(0xFFD9EDE4),
    aviso = Color(0xFF8C5300),
    avisoSuave = Color(0xFFF8E7CC),
    critico = Color(0xFF9C2F2A),
    criticoSuave = Color(0xFFF8DCD8),
    urgCalma = Color(0xFF5F7064),
    urgPerdida = Color(0xFF857987),
    lineaUniversidad = Color(0xFF1D5A60),
    lineaExamen = Color(0xFF7A3A6C),
    info = Color(0xFF38578F),
    urgProxima = Color(0xFF1D5A60),
    urgPronto = Color(0xFF8C5300),
    urgSalir = Color(0xFFAD3C24),
    urgUrgente = Color(0xFF9C2F2A),
    esNoche = false,
)

val AgendaDsNoche = AgendaDs(
    fondo = Color(0xFF15121A),
    superficie = Color(0xFF1F1B25),
    superficieFuerte = Color(0xFF2A2530),
    linea = Color(0xFF3A3442),
    lineaFuerte = Color(0xFF7A7083),
    tinta = Color(0xFFF3EDE4),
    tintaSuave = Color(0xFFB6AAB7),
    deshabilitado = Color(0xFF5F5766),
    ruta = Color(0xFF7CC4C4),
    rutaSuave = Color(0xFF173539),
    sobreRuta = Color(0xFF0B1C1E),
    hora = Color(0xFFFF9068),
    horaSuave = Color(0xFF46211A),
    sobreHora = Color(0xFF1B0F0C),
    ciruela = Color(0xFFE3A3D2),
    ciruelaSuave = Color(0xFF3B2137),
    sobreCiruela = Color(0xFF1F0F1B),
    lineaTrabajo = Color(0xFFE2B65C),
    lineaTrabajoSuave = Color(0xFF3A2C10),
    lineaPersonal = Color(0xFFA7C79A),
    lineaPersonalSuave = Color(0xFF22301D),
    lineaEntrega = Color(0xFF9FB7E6),
    lineaEntregaSuave = Color(0xFF1C2740),
    exito = Color(0xFF86D1B5),
    exitoSuave = Color(0xFF163329),
    aviso = Color(0xFFF2B660),
    avisoSuave = Color(0xFF3D2A0C),
    critico = Color(0xFFFF8B80),
    criticoSuave = Color(0xFF45201D),
    urgCalma = Color(0xFF9FB3A5),
    urgPerdida = Color(0xFF8A7F8C),
    lineaUniversidad = Color(0xFF7CC4C4),
    lineaExamen = Color(0xFFE3A3D2),
    info = Color(0xFF9FB7E6),
    urgProxima = Color(0xFF7CC4C4),
    urgPronto = Color(0xFFF2B660),
    urgSalir = Color(0xFFFF9068),
    urgUrgente = Color(0xFFFF8B80),
    esNoche = true,
)
